#!/bin/sh
set -eu

# This scripts prints the version of the snap based on the git tags and the
# current branch. The version is determined as follows:
#
# The highest version tag which is prefixed with "broker-" and is merged into the
# current branch is used as the base version.
# If there is no such tag, "0.0.0" is used as the base version.
#
# If the current commit is tagged, that tag is used as the version as is.
#
# If the current commit is not tagged, the version is appended with the short
# sha of the current commit. When the current branch is not "main", the version
# is further appended with the short sha of the last commit merged from the main
# branch.
#
# Finally, the version is appended with ".dirty" if there are uncommitted changes.

get_version() {
    current_branch=$(git branch --show-current)

    # Get the highest version tag which is prefixed with "broker-"
    tag=$(git -c "versionsort.suffix=-pre" tag --sort=-v:refname --merged="${current_branch}" | grep -E '^broker-' | head -n 1)
    version="${tag}"

    # Strip the "broker-" prefix
    version="${version#broker-}"

    if [ -z "${version}" ]; then
        # No tag found, use "0.0.0"
        version="0.0.0"
    fi

    # If the highest version tag is on the current commit, use it as is after
    # stripping the prefix.
    if [ -n "${tag}" ] && [ "$(git describe --tags --exact-match 2>/dev/null)" = "${tag}" ]; then
        echo "${version}"
        return
    fi

    # Current commit is not tagged, append commit(s) sha.
    version="${version}+$(git rev-parse --short=7 HEAD)"

    # If the current branch is not "main", append the short sha of the last commit
    if [ "${current_branch}" = "main" ]; then
        # Current branch is "main", return the version as is.
        echo "${version}"
        return
    fi

    # Get the short version of the last commit merged from the main branch.
    last_commit_on_main=$(git rev-parse --short=7 "$(git merge-base main HEAD)")
    echo "${version}.${last_commit_on_main}"
}

version=$(get_version)

if ! "${SEMVER:-semver}" check "${version}" >/dev/null; then
    echo "Version ${version} is not a valid semantic version."
    exit 1
fi

# append ".dirty" if there are uncommitted changes.
if [ -n "$(git status --porcelain)" ]; then
    version="${version}.dirty"
fi

echo "${version}"
