name: build-deb (reusable)

on:
  workflow_call:
    inputs:
      files-hash:
        description: 'Hash of build-relevant files, used as cache key and concurrency group'
        type: string
        required: true
      ubuntu-version:
        description: 'Ubuntu version to build the Debian package for'
        type: string
        required: true
    outputs:
      run-id:
        value: ${{ jobs.build-deb.outputs.run-id }}
      pkg-name:
        value: ${{ jobs.build-deb.outputs.pkg-name }}
      pkg-version:
        value: ${{ jobs.build-deb.outputs.pkg-version }}
      pkg-dsc:
        value: ${{ jobs.build-deb.outputs.pkg-dsc }}
      pkg-src-changes:
        value: ${{ jobs.build-deb.outputs.pkg-src-changes }}

concurrency:
  # Avoid rebuilding the same Debian package multiple times in parallel.
  # Instead, wait for the first run to finish. Subsequent runs will then just
  # restore the cached Debian package and skip the build.
  group: build-deb-${{ inputs.files-hash }}-${{ inputs.ubuntu-version }}
  cancel-in-progress: false

env:
  CARGO_VENDOR_FILTERER_VERSION: 0.5.16

jobs:
  build-deb:
    name: Build Debian package
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ github.run_id }}
      pkg-name: ${{ steps.outputs.outputs.pkg-name }}
      pkg-version: ${{ steps.outputs.outputs.pkg-version }}
      pkg-dsc: ${{ steps.outputs.outputs.pkg-dsc }}
      pkg-src-changes: ${{ steps.outputs.outputs.pkg-src-changes }}

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-oras

      - name: Try to restore deb and sources from OCI registry
        id: restore-cache
        run: |
          set -euo pipefail
          set -x

          echo "${{ secrets.GITHUB_TOKEN }}" \
            | oras login ghcr.io -u "${{ github.actor }}" --password-stdin

          # Try to restore the deb
          OCI_REPO=ghcr.io/${{ github.repository }}/authd-deb-${{ inputs.ubuntu-version }}
          OCI_TAG=${{ inputs.files-hash }}
          if ! oras pull "${OCI_REPO}:${OCI_TAG}"; then
            exit 0
          fi
          PKG_DEB=$(find . -maxdepth 1 -name "authd_*.deb")
          [ -n "${PKG_DEB}" ] || exit 1

          # Try to restore the sources
          OCI_REPO=ghcr.io/${{ github.repository }}/authd-deb-sources-${{ inputs.ubuntu-version }}
          if ! oras pull "${OCI_REPO}:${OCI_TAG}"; then
            echo "cache-hit=false" >> "${GITHUB_OUTPUT}"
            exit 0
          fi
          PKG_DSC=$(find . -maxdepth 1 -name "authd_*.dsc")
          PKG_SOURCE_CHANGES=$(find . -maxdepth 1 -name "authd_*.changes")
          PKG_TARBALL=$(find . -maxdepth 1 -name "authd_*.tar*")
          [ -n "${PKG_DSC}" ] || exit 1
          [ -n "${PKG_SOURCE_CHANGES}" ] || exit 1
          [ -n "${PKG_TARBALL}" ] || exit 1

          # Set environment variables for job outputs
          echo "PKG_NAME=$(dpkg-parsechangelog --show-field source)" >> ${GITHUB_ENV}
          echo "PKG_VERSION=$(dpkg-parsechangelog --show-field version)" >> ${GITHUB_ENV}
          echo "PKG_DEB=${PKG_DEB}" >> ${GITHUB_ENV}
          echo "PKG_DSC=${PKG_DSC}" >> ${GITHUB_ENV}
          echo "PKG_SOURCE_CHANGES=${PKG_SOURCE_CHANGES}" >> ${GITHUB_ENV}
          echo "PKG_TARBALL=${PKG_TARBALL}" >> ${GITHUB_ENV}

          echo "cache-hit=true" >> "${GITHUB_OUTPUT}"

      - name: Build Debian package and sources
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: canonical/desktop-engineering/gh-actions/common/build-debian@main
        with:
          docker-image: ubuntu:${{ inputs.ubuntu-version }}
          # Add the Go backports PPA if we're testing a Ubuntu release which
          # doesn't have the required Go version in main.
          extra-apt-repositories: ${{ (inputs.ubuntu-version == 'noble' || inputs.ubuntu-version == 'plucky' || inputs.ubuntu-version == 'questing') && 'ppa:ubuntu-enterprise-desktop/golang' || '' }}
          # Extra build dependencies:
          # - systemd-dev: Required to read compile time variables from systemd via pkg-config.
          extra-source-build-deps: |
            ca-certificates
            git
            libssl-dev
            systemd-dev
          extra-source-build-script: |
            if [ "${{ inputs.ubuntu-version }}" == noble ]; then
              cargo install --locked --root=/usr \
                cargo-vendor-filterer@${{ env.CARGO_VENDOR_FILTERER_VERSION }}
              command -v cargo-vendor-filterer
            fi

            if [ "${{ inputs.ubuntu-version }}" == noble ] || \
               [ "${{ inputs.ubuntu-version }}" == plucky ]; then
              # Avoid lintian warnings on Noble and Plucky by disabling the
              # silent-on-rules-requiring-root tag. That tag doesn't exist in
              # newer versions of lintian so we must only disable it on Noble
              # and Plucky.
              echo "authd source: silent-on-rules-requiring-root [debian/control]" >> debian/source/lintian-overrides
            fi
          allow-sudo: true
          lintian: --fail-on error,warning,info,pedantic --verbose
          run-lrc: true

      - name: Prepare deb and sources for upload
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          set -euo pipefail
          set -x

          # In the next step we upload the deb and sources with 'oras push'.
          # When using a relative file path with that command, that path is
          # preserved and the directory structure is recreated when downloading
          # the file. To avoid that, we copy the files to be uploaded to the
          # working directory and upload them from there.

          # Copy binary deb to working directory. In contrast to the dsc and
          # changes files, the path to the binary deb is not set in the
          # environment by the build-debian action, so we have to find it first.
          DEB_PATH=$(find "${{ env.BUILD_OUTPUT_DIR }}" -maxdepth 1 -name "authd_*.deb")
          PKG_DEB=$(basename "${DEB_PATH}")
          cp "${DEB_PATH}" "${PKG_DEB}"
          echo "PKG_DEB=${PKG_DEB}" >> ${GITHUB_ENV}

          # Copy sources to working directory
          TARBALL_PATH=$(find "${{ env.SOURCE_OUTPUT_DIR }}" -maxdepth 1 -name "authd_*.tar*")
          PKG_TARBALL=$(basename "${TARBALL_PATH}")
          cp "${TARBALL_PATH}" "${PKG_TARBALL}"
          cp "${{ env.SOURCE_OUTPUT_DIR }}/${{ env.PKG_DSC }}" .
          cp "${{ env.SOURCE_OUTPUT_DIR }}/${{ env.PKG_SOURCE_CHANGES }}" .
          echo "PKG_TARBALL=${PKG_TARBALL}" >> ${GITHUB_ENV}

      - name: Upload deb and sources as OCI artifacts
        run: |
          set -euo pipefail
          set -x

          OCI_REPO=ghcr.io/${{ github.repository }}/authd-deb-${{ inputs.ubuntu-version }}
          OCI_TAG=${{ inputs.files-hash }}
          oras push "${OCI_REPO}:${OCI_TAG}" \
            "${{ env.PKG_DEB }}" \
            --artifact-type=application/vnd.debian.binary-package \
            --annotation "org.opencontainers.image.title=authd debian package" \
            --annotation "org.opencontainers.image.version=${{ env.PKG_VERSION }}"
          oras tag "${OCI_REPO}:${OCI_TAG}" "${{ github.sha }}"
          rm "${{ env.PKG_DEB }}"

          OCI_REPO=ghcr.io/${{ github.repository }}/authd-deb-sources-${{ inputs.ubuntu-version }}
          oras push "${OCI_REPO}:${OCI_TAG}" \
            "${{ env.PKG_DSC }}" \
            "${{ env.PKG_SOURCE_CHANGES }}" \
            "${{ env.PKG_TARBALL }}" \
            --artifact-type=application/vnd.debian.source-package \
            --annotation "org.opencontainers.image.title=authd source debian package" \
            --annotation "org.opencontainers.image.version=${{ env.PKG_VERSION }}"
          oras tag "${OCI_REPO}:${OCI_TAG}" "${{ github.sha }}"
          rm "${{ env.PKG_DSC }}" \
             "${{ env.PKG_SOURCE_CHANGES }}" \
             "${{ env.PKG_TARBALL }}"

      - name: Generate outputs
        id: outputs
        run: |
          (
            echo "pkg-name=${{ env.PKG_NAME }}"
            echo "pkg-version=${{ env.PKG_VERSION }}"
            echo "pkg-dsc=${{ env.PKG_DSC }}"
            echo "pkg-src-changes=${{ env.PKG_SOURCE_CHANGES }}"
          ) >> "${GITHUB_OUTPUT}"
